version: '3.3'

services:
  app:
    build:
      context: .
    command: mix phx.server
    logging: &logging
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    volumes:
      - ./:/usr/src/app

volumes:
  home:
